{
    "editor.fontFamily": "Operator Mono Book, Menlo, Monaco, 'Courier New', monospace",
    "editor.fontSize": 14,
    "editor.quickSuggestionsDelay": 30,
    "editor.letterSpacing": 0.5,
    "workbench.editor.tabSizing": "shrink",
    "html.format.enable": true,
    "html.format.preserveNewLines": true,
    "files.trimTrailingWhitespace": true,
    // this isn't really underline but we hack it to be a thicker cursor
    "editor.cursorStyle": "line",
    "editor.wordWrap": "on",
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.fontWeight": "400",
    "editor.cursorBlinking": "solid",
    "editor.colorDecorators": false,
    "workbench.sideBar.location": "left",
    "editor.renderWhitespace": "none",
    "editor.minimap.showSlider": "always",
    "workbench.startupEditor": "newUntitledFile",
    "extensions.ignoreRecommendations": false,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/.next": true
    },
    "workbench.colorTheme": "One Dark Pro",
    "workbench.iconTheme": "material-icon-theme",
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    // show snippets before any other auto completion
    "editor.snippetSuggestions": "top",
    // this lets you quick open multiple items in a row and now have the previous ones closed on you
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "window.title": "${dirty} ${activeEditorMedium}${separator}${rootName}",
    // These are all my auto-save configs
    "editor.formatOnSave": true,
    "cSpell.userWords": [
        "SIGNUP",
        "Signin",
        "Signout",
        "TLDR",
        "Templating",
        "backend",
        "camo",
        "destructure",
        "gmail",
        "injectable",
        "lightgrey",
        "minmax",
        "prefetch",
        "promisify",
        "refetch",
        "Antoni Kepinski",
        "navlink",
        "extlink",
        "esnext",
        "kepinski",
        "Vercel",
        "Kross",
        "Spotify",
        "YubiKey",
        "IntelliCode",
        "dotfiles"
    ],
    "editor.autoIndent": "keep",
    "window.closeWhenEmpty": true,
    "editor.detectIndentation": false,
    "files.insertFinalNewline": true,
    "editor.showFoldingControls": "always",
    "editor.find.seedSearchStringFromSelection": true,
    "editor.matchBrackets": "always",
    "window.openFilesInNewWindow": "off",
    "workbench.editor.enablePreview": true,
    "editor.scrollBeyondLastLine": true,
    "editor.useTabStops": true,
    "editor.formatOnPaste": true,
    "window.zoomLevel": 0,
    "editor.suggestSelection": "first",
    "git.enableSmartCommit": true,
    "git.autofetch": true,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
    "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
    "xo.enable": true,
    "xo.format.enable": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "C_Cpp.updateChannel": "Insiders",
    "editor.defaultFormatter": "samverschueren.linter-xo",
    "editor.formatOnType": true,
    "css.validate": false,
    "editor.quickSuggestions": {
        "strings": true
    },
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "workbench.enableExperiments": false,
    "files.autoSave": "afterDelay",
    "typescript.tsserver.log": "verbose",
    "editor.suggest.insertMode": "replace",
    "material-icon-theme.activeIconPack": "react",
    "editor.accessibilitySupport": "off",
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ]
}
